export const GROUP_ICONS = [
  { name: 'sports_bar', label: 'Cerveja' },
  { name: 'liquor', label: 'Destilado' },
  { name: 'wine_bar', label: 'Vinho' },
  { name: 'local_bar', label: 'Drink' },
  { name: 'nightlife', label: 'Balada' },
  { name: 'water_drop', label: 'Água' },
  { name: 'local_drink', label: 'Copo' },
  { name: 'emoji_food_beverage', label: 'Chá' },
  { name: 'local_cafe', label: 'Café' },
  { name: 'restaurant', label: 'Restaurante' },
  { name: 'lunch_dining', label: 'Lanche' },
  { name: 'fastfood', label: 'Fast food' },
  { name: 'local_pizza', label: 'Pizza' },
  { name: 'tapas', label: 'Petisco' },
  { name: 'set_meal', label: 'Prato' },
  { name: 'kebab_dining', label: 'Espeto' },
  { name: 'ramen_dining', label: 'Caldo' },
  { name: 'egg', label: 'Ovo' },
  { name: 'bakery_dining', label: 'Padaria' },
  { name: 'cake', label: 'Sobremesa' },
  { name: 'icecream', label: 'Sorvete' },
  { name: 'cookie', label: 'Doce' },
  { name: 'nutrition', label: 'Fruta' },
  { name: 'eco', label: 'Natural' },
  { name: 'storefront', label: 'Mercearia' },
  { name: 'shopping_basket', label: 'Cesta' },
  { name: 'local_grocery_store', label: 'Mercado' },
  { name: 'smoking_rooms', label: 'Cigarro' },
  { name: 'kitchen', label: 'Cozinha' },
  { name: 'cleaning_services', label: 'Limpeza' },
  { name: 'ac_unit', label: 'Gelo' },
  { name: 'inventory_2', label: 'Estoque' },
];

export const EXPENSE_ICONS = [
  { name: 'local_shipping', label: 'Entrega' },
  { name: 'payments', label: 'Pagamento' },
  { name: 'receipt_long', label: 'Nota' },
  { name: 'request_quote', label: 'Orçamento' },
  { name: 'credit_card', label: 'Cartão' },
  { name: 'account_balance', label: 'Banco' },
  { name: 'savings', label: 'Reserva' },
  { name: 'home', label: 'Aluguel' },
  { name: 'bolt', label: 'Energia' },
  { name: 'water_drop', label: 'Água' },
  { name: 'wifi', label: 'Internet' },
  { name: 'local_gas_station', label: 'Combustível' },
  { name: 'build', label: 'Manutenção' },
  { name: 'handyman', label: 'Reparo' },
  { name: 'cleaning_services', label: 'Limpeza' },
  { name: 'badge', label: 'Funcionário' },
  { name: 'person', label: 'Pessoa' },
  { name: 'groups', label: 'Equipe' },
  { name: 'delivery_dining', label: 'Delivery' },
  { name: 'campaign', label: 'Marketing' },
  { name: 'devices', label: 'Aparelhos' },
  { name: 'computer', label: 'Software' },
  { name: 'phone_iphone', label: 'Telefone' },
  { name: 'security', label: 'Segurança' },
  { name: 'gavel', label: 'Jurídico' },
  { name: 'medical_services', label: 'Saúde' },
  { name: 'school', label: 'Treinamento' },
  { name: 'celebration', label: 'Evento' },
  { name: 'music_note', label: 'Música' },
  { name: 'storefront', label: 'Loja' },
];

export const GENERAL_ICONS = [
  { name: 'category', label: 'Categoria' },
  { name: 'label', label: 'Etiqueta' },
  { name: 'sell', label: 'Preço' },
  { name: 'folder', label: 'Pasta' },
  { name: 'widgets', label: 'Blocos' },
  { name: 'grid_view', label: 'Grade' },
  { name: 'layers', label: 'Camadas' },
  { name: 'star', label: 'Estrela' },
  { name: 'favorite', label: 'Favorito' },
  { name: 'bookmark', label: 'Marcador' },
  { name: 'flag', label: 'Bandeira' },
  { name: 'push_pin', label: 'Fixar' },
  { name: 'lightbulb', label: 'Ideia' },
  { name: 'extension', label: 'Extra' },
  { name: 'all_inclusive', label: 'Geral' },
  { name: 'more_horiz', label: 'Outros' },
];

const KNOWN = new Set([...GROUP_ICONS, ...EXPENSE_ICONS, ...GENERAL_ICONS].map((item) => item.name));

export function cleanIcon(value, fallback = 'category') {
  const name = String(value || '').trim();
  return KNOWN.has(name) ? name : fallback;
}
