export const overviewFallback = {
  metrics: [
    {
      id: 'revenue',
      label: 'Faturamento Diário',
      value: 'R$ 14.850,00',
      badge: '+12.5%',
      badgeTone: 'positive',
      icon: 'payments',
    },
    {
      id: 'freela-cost',
      label: 'Custo de Freelas Hoje',
      value: 'R$ 620,00',
      badge: '4 Ativos',
      badgeTone: 'neutral',
      icon: 'engineering',
    },
    {
      id: 'stock-alert',
      label: 'Alerta de Estoque',
      value: '3 Itens',
      badge: 'CRÍTICO',
      badgeTone: 'critical',
      icon: 'warning',
    },
  ],
  weeklyPerformance: [
    { day: 'SEG', revenue: 65, expense: 40, highlight: false },
    { day: 'TER', revenue: 75, expense: 35, highlight: false },
    { day: 'QUA', revenue: 95, expense: 30, highlight: true },
    { day: 'QUI', revenue: 85, expense: 45, highlight: false },
    { day: 'SEX', revenue: 90, expense: 50, highlight: false },
    { day: 'SÁB', revenue: 98, expense: 40, highlight: false },
    { day: 'DOM', revenue: 80, expense: 30, highlight: false },
  ],
  topSold: [
    {
      id: 1,
      name: 'Negroni Clássico',
      category: 'Coquetelaria',
      orders: 124,
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBuCHK5wpr6u_99q5uEEkAgfKIRbU9Mx4ntCaCTUcURZVJuXFz2C2J6_PcN6odgSySrH2QlkbdJquzfCt8lwEZANlXUd5pCnF7OTOb_Dpks0fDU9ob-8kL06uzuR9HrlB8Gnp_rTGT9G8ojhd1otT1Lg2TAwhnCbCretIE2eqL5Biy8sW_g2bpHGtFxYNKuo3r_GxfSmX2GeSiRiEgWa8ntp_FOB9mPEJxVrMVqxJKvniwtte4C4wn3c4ovGNtHGNZJt4ER8NqRvs0t',
      rankTone: 'secondary',
    },
    {
      id: 2,
      name: 'IPA Artesanal',
      category: 'Cervejas',
      orders: 98,
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCEGWTKXscF9RpLHHUKIhPvy-yW8ha7IPrRVBPGDL8N1CKaQMRGiz719YqBuO5gY6OUaHtAHqHqTXVcesKsv3vAYGE4phbRUzsXOQa9RU5GP7NPiWF_TODctO-uEaMZcMB8ZOtLu6jS9O5uEmiRKRRqj6gwCjG7rDC9hDDT4cPAJMeYbFK5oVVOg3IqD5s_mANYoAhWoBatRBVDVxyORQTrpKCuJ7fjJAfQYuIVagWpG-ccQM4rtLYQko5MQbxdIY53AD9hJIvaB3xE',
      rankTone: 'slate',
    },
    {
      id: 3,
      name: 'Gin Tônica Premium',
      category: 'Coquetelaria',
      orders: 82,
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuAmX1XAKBcil8jYhcmNZgZmDg_HZ0iXeeJ11O4As-1pcIyYetMyrttwd-QJwW6OP0JnxxDG-f-LkNN5AOdYwfT4mg5j_yY90nMZlNsXPNANCBxDhDJDtSkpgY2fa8WAKS0ZPk8iLuEB4EHzRM-W3_x-asVD65Xvc965he7js2Qj14llKtzv8s1EVHa-pIWZ3H-LkyrJFv_T8OiFseM47zCGSKm3U8_zW6FkmyxdR2ppjYQfRud69TrBzEd0UT7hgQ3cZt6ehxvKVDhL',
      rankTone: 'muted',
    },
    { id: 4, name: 'Tábua de Frios', category: 'Petiscos', orders: 74, icon: 'fastfood' },
    { id: 5, name: 'Margarita', category: 'Coquetelaria', orders: 66, icon: 'local_bar' },
  ],
  suggestion: {
    title: 'Otimize seu Estoque de Destilados',
    description:
      'Detectamos que a saída de Gin Beefeater aumentou 40% este mês. Gostaria de automatizar o pedido de reposição?',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCNt6UIQlkTELByPX0sgXYzqujQ639Hz_JiLAHZVRUFgKwThpAwhj0__3pMkZMsUZ9eqbcMTLD3IzIhSPHK5Q2lEV8o-cLvy-2BDXHvc7j7cAuzieGY__o2pMFJm0RTNMPIclqVWJKqAA_KO3qDgFNqOYsCh7CHHi8qckb6sCFS-enfoHmJHWs3WV1TP4I3M4jAvCfRwWVDoOOw5lgL3uldKUBDEQhpEhjgD4wRqIFDWIyKgh0LRzKlQCcR0NzCPMSryk1Uc2hLAGG8',
  },
};

export const expenseCategories = [
  { id: 'bebidas', name: 'Bebidas', type: 'expense', defaultNature: 'variable', icon: 'local_shipping' },
  { id: 'freelancer', name: 'Freelancer', type: 'expense', defaultNature: 'variable', icon: 'person' },
  { id: 'suprimentos', name: 'Suprimentos', type: 'expense', defaultNature: 'variable', icon: 'ac_unit' },
  { id: 'utilidades', name: 'Utilidades', type: 'expense', defaultNature: 'fixed', icon: 'bolt' },
  { id: 'aluguel', name: 'Aluguel', type: 'expense', defaultNature: 'fixed', icon: 'home' },
  { id: 'software', name: 'Software', type: 'expense', defaultNature: 'fixed', icon: 'devices' },
  { id: 'salarios', name: 'Salários', type: 'expense', defaultNature: 'fixed', icon: 'badge' },
  { id: 'manutencao', name: 'Manutenção', type: 'expense', defaultNature: 'variable', icon: 'build' },
];

export const cashFlowFallback = {
  period: 'Outubro 2023',
  categories: expenseCategories,
  incomes: [
    {
      id: 'inc-1',
      date: '12 Out',
      description: 'Vendas PDV (Cartão)',
      category: 'Varejo',
      categoryIcon: 'shopping_cart',
      categoryTone: 'secondary',
      value: 'R$ 14.500,00',
      amount: 1450000,
    },
    {
      id: 'inc-2',
      date: '10 Out',
      description: 'Evento Privado: Lançamento Tech',
      category: 'Eventos',
      categoryIcon: 'celebration',
      categoryTone: 'tertiary',
      value: 'R$ 8.200,00',
      amount: 820000,
    },
    {
      id: 'inc-3',
      date: '08 Out',
      description: 'Reserva de Mesa VIP (Sinal)',
      category: 'Reservas',
      categoryIcon: 'confirmation_number',
      categoryTone: 'secondary',
      value: 'R$ 1.250,00',
      amount: 125000,
    },
    {
      id: 'inc-4',
      date: '05 Out',
      description: 'Vendas PDV (Dinheiro)',
      category: 'Varejo',
      categoryIcon: 'payments',
      categoryTone: 'secondary',
      value: 'R$ 3.420,00',
      amount: 342000,
    },
  ],
  expenses: [
    {
      id: 'exp-1',
      date: '14 Out',
      supplier: 'Ambev S.A.',
      category: 'Bebidas',
      categoryId: 'bebidas',
      categoryIcon: 'local_shipping',
      nature: 'variable',
      value: 'R$ 5.400,00',
      amount: 540000,
      recurrence: null,
      source: 'manual',
    },
    {
      id: 'exp-2',
      date: '12 Out',
      supplier: 'Ricardo Alves (Barman)',
      category: 'Freelancer',
      categoryId: 'freelancer',
      categoryIcon: 'person',
      nature: 'variable',
      value: 'R$ 450,00',
      amount: 45000,
      recurrence: null,
      source: 'freelancer_daily',
    },
    {
      id: 'exp-3',
      date: '11 Out',
      supplier: 'Distribuidora de Gelo',
      category: 'Suprimentos',
      categoryId: 'suprimentos',
      categoryIcon: 'ac_unit',
      nature: 'variable',
      value: 'R$ 180,00',
      amount: 18000,
      recurrence: null,
      source: 'manual',
    },
    {
      id: 'exp-4',
      date: '09 Out',
      supplier: 'Enel Distribuidora',
      category: 'Utilidades',
      categoryId: 'utilidades',
      categoryIcon: 'bolt',
      nature: 'fixed',
      value: 'R$ 2.100,00',
      amount: 210000,
      recurrence: 'monthly',
      source: 'manual',
    },
  ],
  summary: {
    totalRevenue: 'R$ 27.370',
    revenueDelta: '12%',
    totalExpenses: 'R$ 8.130',
    expensesDelta: '4%',
    grossProfit: 'R$ 19.240',
    margin: '70% Margem',
    netProfit: 'R$ 15.820',
    fixedExpenses: 'R$ 2.100',
    variableExpenses: 'R$ 6.030',
    contributionMargin: 'R$ 21.340',
    estimatedProfit: 'R$ 19.240',
    variableShare: '22%',
  },
};

export const inventoryFallback = {
  filters: ['Todos', 'Cervejas', 'Destilados', 'Insumos', 'Soft Drinks'],
  items: [
    {
      id: 1,
      name: 'Gin Beefeater',
      subtitle: 'London Dry Gin',
      category: 'Destilados',
      stock: '4 garrafas',
      minStock: '5 garrafas',
      cost: 'R$ 120,00',
      status: 'low',
      statusLabel: 'Estoque Baixo',
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCy6mHO6BQ3jHkOXYMkgzfNMR5XOp9cmvJG__q8UqOJxzYYlP0hInuBeukbHujd7ZDyzNtjkAyb4O0_R1lrdEf_sBbjAs5KSZOah5hT0Ao9ntnRzlMcNcIcYVHytXJSl7-Inuw9tOXRRDpv-kzg4jyL7pN4K_SnvX2DUAIOGmmYK1aHgQj_Ee_RoUw19U9JH-9yR-ufw2dXXpSVujtmSThXMrqbffpKX4pi0gB9s6sz1lTOdVmTKWxP2lTAS0b3fWpAyBo3FvKaKhlJ',
    },
    {
      id: 2,
      name: 'IPA Artesanal',
      subtitle: 'Hoppy Heaven Brewery',
      category: 'Cervejas',
      stock: '48 latas',
      minStock: '24 latas',
      cost: 'R$ 12,00',
      status: 'stable',
      statusLabel: 'Estável',
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuAbyX2JpDEppRTaTQ3Vrjl7MyoWasgbq89qalYBovP9kuSc2u5o6q5M_ZoadK75ivseyzSLw2ynuDZkEVolh3g62t1DNC8m24Zq81yMwahJ4-R5kudxhbnkKy7kjWRQw6EQxIRTNSK9aoYXEmbtcqd-tndFo65rLcJJicFCZM8LMna_QRCO-hl13EA7oeiQHh9SKnlA3zS2tYyLdihfF42bc7CFofuSzRxIEd3KD5WO79rjv3DVgu9xJDgeY4p5BjpvyiYfR8tJ3LRj',
    },
    {
      id: 3,
      name: 'Gelo (Saco 5kg)',
      subtitle: 'Crystal Ice Co.',
      category: 'Insumos',
      stock: '12 sacos',
      minStock: '5 sacos',
      cost: 'R$ 8,00',
      status: 'stable',
      statusLabel: 'Estável',
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuATrb95GgrifNn5ZTFGKBOO3ST2xuzttKMuPO21tPew8Bzeb3UowFhw7W7JPuHD03armjXVgDMfWq79f_IxkS6Ant9g94kkvwghZGZz1tY_d-a1jqeZXTPyjUoEuQj3UzPK_KUKPOtL0yJA_Jqp9HA2EAh3wnjfpNPk8OEGoMmnqpuQ4txI8OKgIIPruQWqYtqLABnNoiIjSvCr1J3TujAb_QMUY71yBS2sQvj2j9OfKsyH2lckNOcmk1Lp6U5MJeVvbUlS7b3z4cVl',
    },
  ],
  metrics: [
    {
      id: 'low-stock',
      tone: 'error',
      badge: 'Ação Necessária',
      icon: 'warning',
      label: 'Itens em Estoque Baixo',
      value: '12',
      progress: 65,
    },
    {
      id: 'inventory-value',
      tone: 'secondary',
      badge: 'Ativo',
      icon: 'inventory',
      label: 'Valor Total do Inventário',
      value: 'R$ 14.850,00',
      progress: 45,
    },
    {
      id: 'turnover',
      tone: 'tertiary',
      badge: 'Eficiência',
      icon: 'trending_up',
      label: 'Giro de Estoque (Mês)',
      value: '4.2x',
      progress: 80,
    },
  ],
};

export const freelancersFallback = {
  roles: ['Barman', 'Garçom', 'Cozinha'],
  people: [
    {
      id: 1,
      name: 'Ricardo Alves',
      role: 'Head Mixologist',
      status: 'on_shift',
      statusLabel: 'Em turno',
      dailyRate: 'R$ 280,00',
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBLUK_0nt1iOMXY4isHF_UpbtSOlSxkTjnXRly3vOscbot3g3xAhqe0vcX6FsT9wnRS-r_knQw4sOkeihz8A__vWSS8JWNI9jxJFSNElJiRdcnXwzvH73D6LasUeIDTtc7la-RFta_Y-vYvnZ5qnLjjEv00bo7bahCl3F5TXPB3WVC-KUTwTnVm59MA9_cq3tADmM3BepB4xfTwYQfswxZR7OHski_jooCy-Y1RiShLxne-taSYSbfkK-y6d8xkyDrOu8A6wczWf63E',
    },
    {
      id: 2,
      name: 'Marina Santos',
      role: 'Garçonete Senior',
      status: 'pending_payment',
      statusLabel: 'Pendente Pgto',
      dailyRate: 'R$ 190,00',
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuA3GQiUc-iSWamBKQ5iZPc3yv4M7R4owb_P1jaPftGrgkCr3hr6g_7y3EucQhU97Xlrw3q5AL5ouWfVf26sJOmZ5yWQu2sR9-6ij9mk0UWLMl00Bn8irTtScQLBPewJz18WDYm5n_ni2HlHiB43UwdpTtFTYMX8gLQ6DOikxE0aGY_uw0ZBzO8YEKoWWZF9ljg8MynLi7s5BqA0GJRjlTszVsBHsInUBYbeJMIVAczKFKmwseMXuJB_3GF6qGLKSIIchfO4T3NwmgCd',
    },
    {
      id: 3,
      name: 'Lucas Silva',
      role: 'Cozinha / Parrilla',
      status: 'available',
      statusLabel: 'Disponível',
      dailyRate: 'R$ 250,00',
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBMP-StxQk1Ux8rAkKle80LaxVpq9vn2_oTqN00trgCXjICxv5VkEFyc5mkG3MNlRpIyivayVPiSbxEL2NE-XqphtWKI7pSl0eBEl-N_dPfPANyyiSca7RCxzK0rReFmW3n8emsX1p4UKRcqTTatlEuAFem3M8KdJo5xtxDO3IJnsmR8LCULhe938bp3DD6mrLIUAeMgTUk6eyjN2DZzh4jrkiJgzFQXDwj2Q1wv4P9ij5hXyb1qPnUjmVieRvlsJUOWCyYT6Cxtm-u',
    },
    {
      id: 4,
      name: 'Ana Beatriz',
      role: 'Hostess',
      status: 'on_shift',
      statusLabel: 'Em turno',
      dailyRate: 'R$ 150,00',
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCNeG1q_kub0NHVdZb0Ed-ELi1qp3bgJoTkL7Z91lLVvBVCyxlOsa3YVWH0yBw4XUpSniMONBXk8Re3hlP7FOxW_KYjc54mnblafSea1xkZrONUDj2AFWuyLa3r9T6OABbH34nTMrBAhuVQRtAw_LRXMA4Te9HiATc4LfX0ba_c1sjO7GbxRXJ1o6iTnFuPSewAByIyWlYBgH-S1LrVieaI1SAIYvV8VEyjxbg-zYT_Rrm_FOTPHVKRLTXEbg1g7-R_0ekMkLAeJOiY',
    },
  ],
  summary: { costsToday: 'R$ 430', activeNow: '02' },
};
