/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: {
        outline: '#D4D4D4',
        'error-container': '#fb5151',
        'on-tertiary-container': '#111111',
        surface: '#FFFFFF',
        'on-primary-container': '#111111',
        'tertiary-container': '#F0F0F0',
        'primary-dim': '#E6C400',
        'on-secondary-fixed-variant': '#111111',
        'tertiary-fixed-dim': '#D4D4D4',
        'tertiary-dim': '#3D3D3D',
        'primary-fixed': '#FFDB15',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F7F7F7',
        'secondary-fixed': '#FFDB15',
        'on-background': '#111111',
        'secondary-container': '#FFDB15',
        error: '#B31B25',
        tertiary: '#3D3D3D',
        'surface-dim': '#E5E5E5',
        primary: 'var(--color-primary, #FFDB15)',
        background: '#FFFFFF',
        'primary-container': '#FFDB15',
        'surface-container-high': '#EBEBEB',
        'on-primary-fixed-variant': '#111111',
        'on-secondary': '#FFFFFF',
        'on-primary': '#111111',
        'on-surface': '#111111',
        'inverse-surface': '#111111',
        'primary-fixed-dim': '#E6C400',
        'surface-bright': '#FFFFFF',
        secondary: '#111111',
        'on-error': '#FFFFFF',
        'on-tertiary-fixed-variant': '#111111',
        'secondary-fixed-dim': '#E6C400',
        'surface-container-highest': '#E0E0E0',
        'on-tertiary-fixed': '#111111',
        'on-secondary-fixed': '#111111',
        'on-error-container': '#570008',
        'on-tertiary': '#FFFFFF',
        'surface-variant': '#E8E8E8',
        'on-primary-fixed': '#111111',
        'on-surface-variant': '#5C5C5C',
        'inverse-primary': '#FFDB15',
        'on-secondary-container': '#111111',
        'secondary-dim': '#000000',
        'outline-variant': '#E5E5E5',
        'tertiary-fixed': '#F0F0F0',
        'inverse-on-surface': '#FFFFFF',
        'surface-tint': '#FFDB15',
        'error-dim': '#9f0519',
        'surface-container': '#F0F0F0',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
};
